version: "3.8"
services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres
        ports:
            - "5432:5432"
        volumes:
            - ../../data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
            POSTGRES_DB: vector
        networks:
            - local

networks:
    local:
        driver: bridge
